services:
    # ==========================================
    # 1. Database: PostgreSQL
    # ==========================================
    postgres-db:
        image: postgres:16
        container_name: game-database
        restart: always
        env_file:
            - ./server/.env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    # ==========================================
    # 2. Database GUI: pgAdmin
    # ==========================================
    pgadmin:
        image: dpage/pgadmin4
        container_name: game-pgadmin
        restart: always
        env_file:
            - ./server/.env
        ports:
            - "5050:80"
        depends_on:
            - postgres-db

    # ==========================================
    # 3. API Gateway: Spring Boot
    # ==========================================
    backend:
        build:
            context: ./server
        container_name: spring-api
        ports:
            - "8080:8080"
        env_file:
            - ./server/.env
        depends_on:
            - postgres-db

    frontend:
        build:
            context: ./frontend
        container_name: react-client
        command: sh -c "npm install && npm run build && npm run preview -- --host 0.0.0.0 --port 5173"
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        env_file:
            - ./frontend/.env
        environment:
            CHOKIDAR_USEPOLLING: "true"
        depends_on:
            - backend

volumes:
    pgdata:
