package com.example.botfight.DTO;

import java.time.Instant;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonInclude;
import tools.jackson.databind.JsonNode;

@JsonInclude(JsonInclude.Include.NON_NULL)
public record MatchmakingEventDTO(
        String type,
        UUID matchId,
        Long simulationSeed,
        String status,
        MatchmakingPlayerDTO player,
        MatchmakingPlayerDTO opponent,
        List<MatchmakingPlayerDTO> players,
        Instant serverNow,
        Instant loadoutSelectionEndsAt,
        Instant entityPlacementEndsAt,
        Instant countdownEndsAt,
        Instant buildingEndsAt,
        Instant playbackStartsAt,
        Instant resultRevealsAt,
        String rulesetVersion,
        MatchReplayDTO playback,
        Integer roundNumber,
        Integer winsRequired,
        String message,
        UUID entityPlacementUserId,
        List<MatchPlaybackDTO.ArenaEntityDTO> entityPlacements,
        List<MatchPlaybackDTO.ArenaEntityDTO> arenaEntities,
        List<RoundBrainDTO> roundBrains,
        Boolean previousRoundWon,
        List<Integer> abilityOffers,
        Integer roundBlockLimit,
        UUID disconnectedUserId,
        Instant disconnectEndsAt,
        Long simulationPreparingDurationMs,
        Instant roundReadyAt,
        Instant matchChatEndsAt,
        Instant matchAcceptanceEndsAt,
        Boolean acceptedByMe,
        Boolean otherPlayerAccepted,
        String mode,
        Boolean surrenderRequestedByMe,
        Integer surrenderVoteCount,
        Integer surrenderVoteRequired,
        UUID codeViewRequestId,
        UUID codeViewTargetUserId,
        String codeViewTargetUsername,
        JsonNode codeViewBrain,
        String codeViewSelectedLoadout) {

    /** Backward-compatible constructor for the pre-vote 1v1/match contract. */
    public MatchmakingEventDTO(
            String type,
            UUID matchId,
            Long simulationSeed,
            String status,
            MatchmakingPlayerDTO player,
            MatchmakingPlayerDTO opponent,
            List<MatchmakingPlayerDTO> players,
            Instant serverNow,
            Instant loadoutSelectionEndsAt,
            Instant entityPlacementEndsAt,
            Instant countdownEndsAt,
            Instant buildingEndsAt,
            Instant playbackStartsAt,
            Instant resultRevealsAt,
            String rulesetVersion,
            MatchReplayDTO playback,
            Integer roundNumber,
            Integer winsRequired,
            String message,
            UUID entityPlacementUserId,
            List<MatchPlaybackDTO.ArenaEntityDTO> entityPlacements,
            List<MatchPlaybackDTO.ArenaEntityDTO> arenaEntities,
            List<RoundBrainDTO> roundBrains,
            Boolean previousRoundWon,
            List<Integer> abilityOffers,
            Integer roundBlockLimit,
            UUID disconnectedUserId,
            Instant disconnectEndsAt,
            Long simulationPreparingDurationMs,
            Instant roundReadyAt,
            Instant matchChatEndsAt,
            Instant matchAcceptanceEndsAt,
            Boolean acceptedByMe,
            Boolean otherPlayerAccepted,
            String mode) {
        this(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                entityPlacementEndsAt,
                countdownEndsAt,
                buildingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                entityPlacementUserId,
                entityPlacements,
                arenaEntities,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                matchAcceptanceEndsAt,
                acceptedByMe,
                otherPlayerAccepted,
                mode,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }

    /** Backward-compatible constructor for the pre-code-view vote contract. */
    public MatchmakingEventDTO(
            String type,
            UUID matchId,
            Long simulationSeed,
            String status,
            MatchmakingPlayerDTO player,
            MatchmakingPlayerDTO opponent,
            List<MatchmakingPlayerDTO> players,
            Instant serverNow,
            Instant loadoutSelectionEndsAt,
            Instant entityPlacementEndsAt,
            Instant countdownEndsAt,
            Instant buildingEndsAt,
            Instant playbackStartsAt,
            Instant resultRevealsAt,
            String rulesetVersion,
            MatchReplayDTO playback,
            Integer roundNumber,
            Integer winsRequired,
            String message,
            UUID entityPlacementUserId,
            List<MatchPlaybackDTO.ArenaEntityDTO> entityPlacements,
            List<MatchPlaybackDTO.ArenaEntityDTO> arenaEntities,
            List<RoundBrainDTO> roundBrains,
            Boolean previousRoundWon,
            List<Integer> abilityOffers,
            Integer roundBlockLimit,
            UUID disconnectedUserId,
            Instant disconnectEndsAt,
            Long simulationPreparingDurationMs,
            Instant roundReadyAt,
            Instant matchChatEndsAt,
            Instant matchAcceptanceEndsAt,
            Boolean acceptedByMe,
            Boolean otherPlayerAccepted,
            String mode,
            Boolean surrenderRequestedByMe,
            Integer surrenderVoteCount,
            Integer surrenderVoteRequired) {
        this(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                entityPlacementEndsAt,
                countdownEndsAt,
                buildingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                entityPlacementUserId,
                entityPlacements,
                arenaEntities,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                matchAcceptanceEndsAt,
                acceptedByMe,
                otherPlayerAccepted,
                mode,
                surrenderRequestedByMe,
                surrenderVoteCount,
                surrenderVoteRequired,
                null,
                null,
                null,
                null,
                null);
    }

    /** Binary/source-compatible constructor for clients and fixtures from the 1v1 contract. */
    public MatchmakingEventDTO(
            String type,
            UUID matchId,
            Long simulationSeed,
            String status,
            MatchmakingPlayerDTO player,
            MatchmakingPlayerDTO opponent,
            List<MatchmakingPlayerDTO> players,
            Instant serverNow,
            Instant loadoutSelectionEndsAt,
            Instant entityPlacementEndsAt,
            Instant countdownEndsAt,
            Instant buildingEndsAt,
            Instant playbackStartsAt,
            Instant resultRevealsAt,
            String rulesetVersion,
            MatchReplayDTO playback,
            Integer roundNumber,
            Integer winsRequired,
            String message,
            UUID entityPlacementUserId,
            List<MatchPlaybackDTO.ArenaEntityDTO> entityPlacements,
            List<MatchPlaybackDTO.ArenaEntityDTO> arenaEntities,
            List<RoundBrainDTO> roundBrains,
            Boolean previousRoundWon,
            List<Integer> abilityOffers,
            Integer roundBlockLimit,
            UUID disconnectedUserId,
            Instant disconnectEndsAt,
            Long simulationPreparingDurationMs,
            Instant roundReadyAt,
            Instant matchChatEndsAt,
            Instant matchAcceptanceEndsAt,
            Boolean acceptedByMe,
            Boolean otherPlayerAccepted) {
        this(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                entityPlacementEndsAt,
                countdownEndsAt,
                buildingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                entityPlacementUserId,
                entityPlacements,
                arenaEntities,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                matchAcceptanceEndsAt,
                acceptedByMe,
                otherPlayerAccepted,
                null,
                null,
                null,
                null);
    }

    public MatchmakingEventDTO withReplayParticipants(
            MatchmakingPlayerDTO replayPlayer,
            MatchmakingPlayerDTO replayOpponent,
            List<MatchmakingPlayerDTO> replayPlayers) {
        return new MatchmakingEventDTO(
                type,
                matchId,
                simulationSeed,
                status,
                replayPlayer,
                replayOpponent,
                replayPlayers,
                serverNow,
                loadoutSelectionEndsAt,
                entityPlacementEndsAt,
                countdownEndsAt,
                buildingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                entityPlacementUserId,
                entityPlacements,
                arenaEntities,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                matchAcceptanceEndsAt,
                acceptedByMe,
                otherPlayerAccepted,
                mode,
                surrenderRequestedByMe,
                surrenderVoteCount,
                surrenderVoteRequired,
                codeViewRequestId,
                codeViewTargetUserId,
                codeViewTargetUsername,
                codeViewBrain,
                codeViewSelectedLoadout);
    }

    public static MatchmakingEventDTO replayBatchPayload(
            UUID matchId,
            String rulesetVersion,
            MatchReplayDTO playback,
            Instant playbackStartsAt,
            Instant resultRevealsAt,
            Instant roundReadyAt) {
        return replayBatchPayload(
                matchId,
                rulesetVersion,
                playback,
                playbackStartsAt,
                resultRevealsAt,
                roundReadyAt,
                null);
    }

    public static MatchmakingEventDTO replayBatchPayload(
            UUID matchId,
            String rulesetVersion,
            MatchReplayDTO playback,
            Instant playbackStartsAt,
            Instant resultRevealsAt,
            Instant roundReadyAt,
            Integer roundNumber) {
        return new MatchmakingEventDTO(
                "MATCH_REPLAY_BATCH", matchId, null, "READY_FOR_PLAYBACK",
                null, null, null, null, null, null, null, null,
                playbackStartsAt, resultRevealsAt, rulesetVersion, playback,
                roundNumber, null, null, null, null, null, null, null,
                null, null, null, null, null, roundReadyAt,
                null, null, null, null, null);
    }

    public MatchmakingEventDTO(
            String type,
            UUID matchId,
            Long simulationSeed,
            String status,
            MatchmakingPlayerDTO player,
            MatchmakingPlayerDTO opponent,
            List<MatchmakingPlayerDTO> players,
            Instant serverNow,
            Instant loadoutSelectionEndsAt,
            Instant entityPlacementEndsAt,
            Instant countdownEndsAt,
            Instant buildingEndsAt,
            Instant playbackStartsAt,
            Instant resultRevealsAt,
            String rulesetVersion,
            MatchReplayDTO playback,
            Integer roundNumber,
            Integer winsRequired,
            String message,
            UUID entityPlacementUserId,
            List<MatchPlaybackDTO.ArenaEntityDTO> entityPlacements,
            List<MatchPlaybackDTO.ArenaEntityDTO> arenaEntities,
            List<RoundBrainDTO> roundBrains,
            Boolean previousRoundWon,
            List<Integer> abilityOffers,
            Integer roundBlockLimit) {
        this(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                entityPlacementEndsAt,
                countdownEndsAt,
                buildingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                entityPlacementUserId,
                entityPlacements,
                arenaEntities,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }

    public MatchmakingEventDTO(
            String type,
            UUID matchId,
            Long simulationSeed,
            String status,
            MatchmakingPlayerDTO player,
            MatchmakingPlayerDTO opponent,
            List<MatchmakingPlayerDTO> players,
            Instant serverNow,
            Instant loadoutSelectionEndsAt,
            Instant entityPlacementEndsAt,
            Instant countdownEndsAt,
            Instant buildingEndsAt,
            Instant playbackStartsAt,
            Instant resultRevealsAt,
            String rulesetVersion,
            MatchReplayDTO playback,
            Integer roundNumber,
            Integer winsRequired,
            String message,
            UUID entityPlacementUserId,
            List<MatchPlaybackDTO.ArenaEntityDTO> entityPlacements,
            List<MatchPlaybackDTO.ArenaEntityDTO> arenaEntities,
            List<RoundBrainDTO> roundBrains,
            Boolean previousRoundWon,
            List<Integer> abilityOffers,
            Integer roundBlockLimit,
            UUID disconnectedUserId,
            Instant disconnectEndsAt) {
        this(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                entityPlacementEndsAt,
                countdownEndsAt,
                buildingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                entityPlacementUserId,
                entityPlacements,
                arenaEntities,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }

    public MatchmakingEventDTO(
            String type,
            UUID matchId,
            Long simulationSeed,
            String status,
            MatchmakingPlayerDTO player,
            MatchmakingPlayerDTO opponent,
            List<MatchmakingPlayerDTO> players,
            Instant serverNow,
            Instant loadoutSelectionEndsAt,
            Instant entityPlacementEndsAt,
            Instant countdownEndsAt,
            Instant buildingEndsAt,
            Instant playbackStartsAt,
            Instant resultRevealsAt,
            String rulesetVersion,
            MatchReplayDTO playback,
            Integer roundNumber,
            Integer winsRequired,
            String message,
            UUID entityPlacementUserId,
            List<MatchPlaybackDTO.ArenaEntityDTO> entityPlacements,
            List<MatchPlaybackDTO.ArenaEntityDTO> arenaEntities,
            List<RoundBrainDTO> roundBrains,
            Boolean previousRoundWon,
            List<Integer> abilityOffers,
            Integer roundBlockLimit,
            UUID disconnectedUserId,
            Instant disconnectEndsAt,
            Long simulationPreparingDurationMs,
            Instant roundReadyAt,
            Instant matchChatEndsAt) {
        this(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                entityPlacementEndsAt,
                countdownEndsAt,
                buildingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                entityPlacementUserId,
                entityPlacements,
                arenaEntities,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                null,
                null,
                null,
                null);
    }

    public MatchmakingEventDTO withServerNow(Instant actualServerNow) {
        return new MatchmakingEventDTO(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                actualServerNow,
                loadoutSelectionEndsAt,
                entityPlacementEndsAt,
                countdownEndsAt,
                buildingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                entityPlacementUserId,
                entityPlacements,
                arenaEntities,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                matchAcceptanceEndsAt,
                acceptedByMe,
                otherPlayerAccepted,
                mode,
                surrenderRequestedByMe,
                surrenderVoteCount,
                surrenderVoteRequired,
                codeViewRequestId,
                codeViewTargetUserId,
                codeViewTargetUsername,
                codeViewBrain,
                codeViewSelectedLoadout);
    }

    public MatchmakingEventDTO withMode(String nextMode) {
        return new MatchmakingEventDTO(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                entityPlacementEndsAt,
                countdownEndsAt,
                buildingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                entityPlacementUserId,
                entityPlacements,
                arenaEntities,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                matchAcceptanceEndsAt,
                acceptedByMe,
                otherPlayerAccepted,
                nextMode,
                surrenderRequestedByMe,
                surrenderVoteCount,
                surrenderVoteRequired,
                codeViewRequestId,
                codeViewTargetUserId,
                codeViewTargetUsername,
                codeViewBrain,
                codeViewSelectedLoadout);
    }

    public MatchmakingEventDTO withSurrenderState(
            Boolean nextSurrenderRequestedByMe,
            Integer nextSurrenderVoteCount,
            Integer nextSurrenderVoteRequired) {
        return new MatchmakingEventDTO(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                entityPlacementEndsAt,
                countdownEndsAt,
                buildingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                entityPlacementUserId,
                entityPlacements,
                arenaEntities,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                matchAcceptanceEndsAt,
                acceptedByMe,
                otherPlayerAccepted,
                mode,
                nextSurrenderRequestedByMe,
                nextSurrenderVoteCount,
                nextSurrenderVoteRequired,
                codeViewRequestId,
                codeViewTargetUserId,
                codeViewTargetUsername,
                codeViewBrain,
                codeViewSelectedLoadout);
    }

    public MatchmakingEventDTO withCodeViewState(
            UUID nextCodeViewRequestId,
            UUID nextCodeViewTargetUserId,
            String nextCodeViewTargetUsername,
            JsonNode nextCodeViewBrain,
            String nextCodeViewSelectedLoadout) {
        return new MatchmakingEventDTO(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                entityPlacementEndsAt,
                countdownEndsAt,
                buildingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                entityPlacementUserId,
                entityPlacements,
                arenaEntities,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                matchAcceptanceEndsAt,
                acceptedByMe,
                otherPlayerAccepted,
                mode,
                surrenderRequestedByMe,
                surrenderVoteCount,
                surrenderVoteRequired,
                nextCodeViewRequestId,
                nextCodeViewTargetUserId,
                nextCodeViewTargetUsername,
                nextCodeViewBrain,
                nextCodeViewSelectedLoadout);
    }

    public record RoundBrainDTO(int roundNumber, JsonNode brain, boolean won) {
    }
}
