package com.example.botfight.DTO;

import java.time.Instant;
import java.util.List;
import java.util.UUID;
import tools.jackson.databind.JsonNode;

public record MatchmakingEventDTO(
        String type,
        UUID matchId,
        Long simulationSeed,
        String status,
        MatchmakingPlayerDTO player,
        MatchmakingPlayerDTO opponent,
        List<MatchmakingPlayerDTO> players,
        Instant serverNow,
        Instant loadoutSelectionEndsAt,
        Instant objectPlacementEndsAt,
        Instant countdownEndsAt,
        Instant testingEndsAt,
        Instant playbackStartsAt,
        Instant resultRevealsAt,
        String rulesetVersion,
        MatchPlaybackDTO playback,
        Integer roundNumber,
        Integer winsRequired,
        String message,
        UUID objectPlacementUserId,
        List<MatchPlaybackDTO.ObstaclePlacementDTO> objectPlacements,
        List<MatchPlaybackDTO.ObstaclePlacementDTO> obstacles,
        List<RoundBrainDTO> roundBrains,
        Boolean previousRoundWon,
        List<String> abilityOffers,
        Integer roundBlockLimit,
        UUID disconnectedUserId,
        Instant disconnectEndsAt,
        Long simulationPreparingDurationMs,
        Instant roundReadyAt,
        Instant matchChatEndsAt,
        Instant matchAcceptanceEndsAt,
        UUID acceptedUserId) {

    public static MatchmakingEventDTO replayBatch(
            UUID matchId,
            String rulesetVersion,
            MatchPlaybackDTO playback) {
        return new MatchmakingEventDTO(
                "MATCH_REPLAY_BATCH",
                matchId,
                null,
                "READY_FOR_PLAYBACK",
                null,
                null,
                List.of(),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                rulesetVersion,
                playback,
                null,
                null,
                null,
                null,
                List.of(),
                List.of(),
                List.of(),
                null,
                List.of(),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }

    public MatchmakingEventDTO withReplayParticipants(
            MatchmakingPlayerDTO replayPlayer,
            MatchmakingPlayerDTO replayOpponent,
            List<MatchmakingPlayerDTO> replayPlayers) {
        return new MatchmakingEventDTO(
                type,
                matchId,
                simulationSeed,
                status,
                replayPlayer,
                replayOpponent,
                replayPlayers,
                serverNow,
                loadoutSelectionEndsAt,
                objectPlacementEndsAt,
                countdownEndsAt,
                testingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                objectPlacementUserId,
                objectPlacements,
                obstacles,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                matchAcceptanceEndsAt,
                acceptedUserId);
    }

    public MatchmakingEventDTO(
            String type,
            UUID matchId,
            Long simulationSeed,
            String status,
            MatchmakingPlayerDTO player,
            MatchmakingPlayerDTO opponent,
            List<MatchmakingPlayerDTO> players,
            Instant serverNow,
            Instant loadoutSelectionEndsAt,
            Instant objectPlacementEndsAt,
            Instant countdownEndsAt,
            Instant testingEndsAt,
            Instant playbackStartsAt,
            Instant resultRevealsAt,
            String rulesetVersion,
            MatchPlaybackDTO playback,
            Integer roundNumber,
            Integer winsRequired,
            String message,
            UUID objectPlacementUserId,
            List<MatchPlaybackDTO.ObstaclePlacementDTO> objectPlacements,
            List<MatchPlaybackDTO.ObstaclePlacementDTO> obstacles,
            List<RoundBrainDTO> roundBrains,
            Boolean previousRoundWon,
            List<String> abilityOffers,
            Integer roundBlockLimit) {
        this(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                objectPlacementEndsAt,
                countdownEndsAt,
                testingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                objectPlacementUserId,
                objectPlacements,
                obstacles,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }

    public MatchmakingEventDTO(
            String type,
            UUID matchId,
            Long simulationSeed,
            String status,
            MatchmakingPlayerDTO player,
            MatchmakingPlayerDTO opponent,
            List<MatchmakingPlayerDTO> players,
            Instant serverNow,
            Instant loadoutSelectionEndsAt,
            Instant objectPlacementEndsAt,
            Instant countdownEndsAt,
            Instant testingEndsAt,
            Instant playbackStartsAt,
            Instant resultRevealsAt,
            String rulesetVersion,
            MatchPlaybackDTO playback,
            Integer roundNumber,
            Integer winsRequired,
            String message,
            UUID objectPlacementUserId,
            List<MatchPlaybackDTO.ObstaclePlacementDTO> objectPlacements,
            List<MatchPlaybackDTO.ObstaclePlacementDTO> obstacles,
            List<RoundBrainDTO> roundBrains,
            Boolean previousRoundWon,
            List<String> abilityOffers,
            Integer roundBlockLimit,
            UUID disconnectedUserId,
            Instant disconnectEndsAt) {
        this(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                objectPlacementEndsAt,
                countdownEndsAt,
                testingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                objectPlacementUserId,
                objectPlacements,
                obstacles,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                null,
                null,
                null,
                null,
                null);
    }

    public MatchmakingEventDTO(
            String type,
            UUID matchId,
            Long simulationSeed,
            String status,
            MatchmakingPlayerDTO player,
            MatchmakingPlayerDTO opponent,
            List<MatchmakingPlayerDTO> players,
            Instant serverNow,
            Instant loadoutSelectionEndsAt,
            Instant objectPlacementEndsAt,
            Instant countdownEndsAt,
            Instant testingEndsAt,
            Instant playbackStartsAt,
            Instant resultRevealsAt,
            String rulesetVersion,
            MatchPlaybackDTO playback,
            Integer roundNumber,
            Integer winsRequired,
            String message,
            UUID objectPlacementUserId,
            List<MatchPlaybackDTO.ObstaclePlacementDTO> objectPlacements,
            List<MatchPlaybackDTO.ObstaclePlacementDTO> obstacles,
            List<RoundBrainDTO> roundBrains,
            Boolean previousRoundWon,
            List<String> abilityOffers,
            Integer roundBlockLimit,
            UUID disconnectedUserId,
            Instant disconnectEndsAt,
            Long simulationPreparingDurationMs,
            Instant roundReadyAt,
            Instant matchChatEndsAt) {
        this(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                serverNow,
                loadoutSelectionEndsAt,
                objectPlacementEndsAt,
                countdownEndsAt,
                testingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                objectPlacementUserId,
                objectPlacements,
                obstacles,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                null,
                null);
    }

    public MatchmakingEventDTO withServerNow(Instant actualServerNow) {
        return new MatchmakingEventDTO(
                type,
                matchId,
                simulationSeed,
                status,
                player,
                opponent,
                players,
                actualServerNow,
                loadoutSelectionEndsAt,
                objectPlacementEndsAt,
                countdownEndsAt,
                testingEndsAt,
                playbackStartsAt,
                resultRevealsAt,
                rulesetVersion,
                playback,
                roundNumber,
                winsRequired,
                message,
                objectPlacementUserId,
                objectPlacements,
                obstacles,
                roundBrains,
                previousRoundWon,
                abilityOffers,
                roundBlockLimit,
                disconnectedUserId,
                disconnectEndsAt,
                simulationPreparingDurationMs,
                roundReadyAt,
                matchChatEndsAt,
                matchAcceptanceEndsAt,
                acceptedUserId);
    }

    public record RoundBrainDTO(int roundNumber, JsonNode brain, boolean won) {
    }
}
